webtalk_init -webtalk_dir C:/Users/benan/Desktop/Year4_Semester1/Digital_Circuit_Lab/nctu-digital-circuit-lab-2/lab2/lab2.sim/sim_1/behav/xsim/xsim.dir/mmult_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Sep 30 20:04:21 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ae9f7791-39a7-481c-9a85-032679cb4c08" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "222367ff670d4221a6467dbd65a6656b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2400 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6620_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2240503417 -regid "" -xml C:/Users/benan/Desktop/Year4_Semester1/Digital_Circuit_Lab/nctu-digital-circuit-lab-2/lab2/lab2.sim/sim_1/behav/xsim/xsim.dir/mmult_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/benan/Desktop/Year4_Semester1/Digital_Circuit_Lab/nctu-digital-circuit-lab-2/lab2/lab2.sim/sim_1/behav/xsim/xsim.dir/mmult_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/benan/Desktop/Year4_Semester1/Digital_Circuit_Lab/nctu-digital-circuit-lab-2/lab2/lab2.sim/sim_1/behav/xsim/xsim.dir/mmult_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
